export ZSH=$HOME/.oh-my-zsh

# use vim as the visual editor
export VISUAL='mate -w'
export EDITOR=vim

# ensure dotfiles bin directory is loaded first
# WARNING: this is override later by the setting in .zshrc
# I should fix it >.<
export PATH="$HOME/.bin:/usr/local/sbin:$PATH"
export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
export PATH="$ZSH/bin:$PATH"

# Android studio
export PATH="$HOME/Library/Android/sdk/tools:$HOME/Library/Android/sdk/platform-tools:$PATH"

# Python 2 via brew
export PATH="/usr/local/opt/python@2/bin:$PATH"

# Yarn installed via shell script
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Fix PIP's annoying "ValueError: unknown locale: UTF-8"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Local config
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvwrapper
